export default [
  {
    eventName: 'systemError',
    logger: 'system',
    pattern: '',
    message: '{0}',
    sendToTelegram: true,
    enabled: true,
  },
  {
    eventName: 'systemNotice',
    logger: 'system',
    pattern: '',
    message: '{0}',
    sendToTelegram: true,
    enabled: true,
  },
  {
    eventName: 'systemInfo',
    logger: 'system',
    pattern: '',
    message: '{0}',
    sendToTelegram: true,
    enabled: true,
  },
  {
    eventName: 'systemDebug',
    logger: 'system',
    pattern: '',
    message: '{0}',
    sendToTelegram: false,
    enabled: true,
  },
  {
    eventName: 'telegramError',
    logger: 'telegram',
    pattern: '',
    message: 'TelegramError: {0}',
    sendToTelegram: false,
    enabled: true,
  },
]
